# Generated by Django 4.0.1 on 2022-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationentry',
            name='t',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
