# Generated by Django 4.0.1 on 2022-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_waypointentry_locationentry_dcreated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(blank=True, max_length=100, null=True)),
                ('acc', models.FloatField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('t', models.CharField(blank=True, max_length=100, null=True)),
                ('tid', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('tst', models.IntegerField(blank=True, null=True)),
                ('wtst', models.IntegerField(blank=True, null=True)),
                ('dcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='locationentry',
            name='inregions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
