# Generated by Django 4.0.1 on 2022-01-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transitionentry_locationentry_inregions'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationentry',
            name='BSSID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationentry',
            name='SSID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
