# Generated by Django 4.0.1 on 2022-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_locationentry_bssid_alter_locationentry_ssid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationentry',
            name='dtst',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationentryjson',
            name='dtst',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitionentry',
            name='dtst',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypointentry',
            name='dtst',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
