# Generated by Django 4.0.1 on 2022-01-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_locationentry_dtst_locationentryjson_dtst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayPointsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('waypoints', models.ManyToManyField(to='core.WaypointEntry')),
            ],
        ),
    ]
